### ISSUE TITLE
No feedback when the user doesn't select a folder

### ISSUE THREAD

**Issue by dangilbert** [lakscastro/shared-storage#13]
I'm trying to show the user an alert when they haven't selected a folder to let them know their file won't be downloaded, but in the case that no URI is returned from the document tree in openDocumentTree, nothing is sent back to flutter.

I don't know whether it makes sense to do something like `pendingResult.second.success(null)` (or even pass the uri regardless of whether it is null) or to return an error case that would need to be handled in flutter, such as an error saying that no folder was chosen.

If you have a preference I'm happy to open a PR against this.

I'm trying to make use of the latest version from master at the moment as I needed access to some of the code as-yet unreleased on pub.dev.

Thanks!

**Comment by lakscastro** [comment]
Thanks for the issue! As you described, seems like the native never returns when the user don't pick a folder, right?

I think the solution is to return `null` when it happens since it's not a error itself but a user choice

If you want, feel free to open the PR! If I could help to answer questions, let me know

Thanks again!
